jitter/urls.py
from django.urls import path

from . import views

app_name = 'jitter'
urlpatterns = [
    path('', views.BunkView.as_view(), name='bunks'),
    path('<int:pk>/', views.IndividualsView.as_view(), name='individuals'),
    path('newbunkform/', views.get_bunking_users, name='bunk')
]

jitterbunk/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jitter/', include('jitter.urls')),
]

jitter/models.py
from typing import Any
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

class User(models.Model):
    username = models.CharField(max_length=200)
    photo = models.CharField(max_length=200)
    bunks = models.ManyToManyField('Bunk',related_name='bunked_users')
    
    def __str__(self):
        return self.username

class Bunk(models.Model):
    fromU = models.ForeignKey('User', on_delete=models.CASCADE, related_name="fromUser")
    toU = models.ForeignKey('User', on_delete=models.CASCADE, related_name="toUser")
    time = models.TimeField('Time')

    

jitter/forms.py
from django.forms import ModelForm
from django import forms
from .models import Bunk, User
from django.utils import timezone

class bunkSomeoneForm(forms.Form):
    fromUser = forms.ModelChoiceField(queryset=User.objects.all(), label="Person doing the bunking")
    toUser = forms.ModelChoiceField(queryset=User.objects.all(), label="Person being bunked")

jitter/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from .models import User, Bunk
from django.template.response import TemplateResponse
from django.views.generic import TemplateView
from .forms import bunkSomeoneForm

class BunkView(generic.ListView):
    template_name = 'jitter/index.html'
    context_object_name = 'list_of_bunks'
    def get_queryset(self):
        return Bunk.objects.filter(
        time__lte=timezone.now()
    ).order_by('time')

class IndividualsView(generic.DetailView):
    model = User
    template_name = 'jitter/individuals.html'

def get_bunking_users(request):
    if request.method == "POST":
        form = bunkSomeoneForm(request.POST)
        if form.is_valid():
            fUser = form.cleaned_data['fromUser']
            tUser = form.cleaned_data['toUser']
            newBunk = Bunk(fromU=fUser, toU=tUser, time=timezone.now())
            newBunk.save()
            fUser.bunks.add(newBunk)
            tUser.bunks.add(newBunk)
    else:
        form = bunkSomeoneForm()
    return render(request, 'jitter/bunk.html', {'form': form})
        

jitter/templates/jitter/bunk.html
<!DOCTYPE html>
<html>
<head>
    <title>Bunk Someone</title>
</head>
<body>
    <h1>Bunk Someone</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Bunk!</button>
    </form>
</body>
</html>
<p></p>
<a href=../>See all Live Bunks</a>

jitter/templates/jitter/index.html
<h1>Current Bunks:</h1>
<a href=/jitter/newbunkform/>Bunk Someone</a>
{% if list_of_bunks %}
    <ul>
    {% for bunk in list_of_bunks %}
    <li><h2>Bunk {{bunk.id}}</h2><p></p><strong>Time of Bunk:</strong> {{bunk.time}}<p></p><strong>Person doing the bunking:</strong> <a href="{% url 'jitter:individuals' bunk.fromU.id %}">{{bunk.fromU.username }}</a><p></p>
    <img src="{{bunk.fromU.photo}}" alt="From User" style="width:100px;">
    <p></p><strong>Person getting bunked:</strong> <a href="{% url 'jitter:individuals' bunk.toU.id %}">{{bunk.toU.username }}</a></li>
    <img src="{{bunk.toU.photo}}" alt="From User" style="width:100px;">
    {% endfor %}
    </ul>
{% else %}
    <p>No Bunks are available.</p>
{% endif %}

jitter/templates/jitter/individuals.html
<h1>Bunks where {{ user.username }} got bunked:</h1>
{% if user.bunks.exists %}
    <ul>
    {% for bunk in user.bunks.all %}
        {% if bunk.toU == user %}
            <li>
                <h2>Bunk {{ bunk.id }}</h2>
                <p><strong>Time of Bunk:</strong> {{ bunk.time }}</p>
                <p><strong>Person doing the bunking:</strong> <a href="{% url 'jitter:individuals' bunk.fromU.id %}">{{ bunk.fromU.username }}</a></p>
                <p><strong>Person getting bunked:</strong> <a href="{% url 'jitter:individuals' bunk.toU.id %}">{{ bunk.toU.username }}</a></p>
            </li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No Bunks are available.</p>
{% endif %}

<h1>Bunks where {{ user.username }} bunked someone else:</h1>
{% with user_bunked_others=user.fromUser.all %}
{% if user_bunked_others.exists %}
    <ul>
    {% for bunk in user_bunked_others %}
        {% if bunk.fromU == user %}
            <li>
                <h2>Bunk {{ bunk.id }}</h2>
                <p><strong>Time of Bunk:</strong> {{ bunk.time }}</p>
                <p><strong>Person doing the bunking:</strong> <a href="{% url 'jitter:individuals' bunk.fromU.id %}">{{ bunk.fromU.username }}</a></p>
                <p><strong>Person getting bunked:</strong> <a href="{% url 'jitter:individuals' bunk.toU.id %}">{{ bunk.toU.username }}</a></p>
            </li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No Bunks are available.</p>
{% endif %}
{% endwith %}
<a href=../>See all Live Bunks</a>
<p></p>
<a href=/jitter/newbunkform/>Bunk Someone</a>